root: '123456'
bot_uin: '123456789'
debug: false
check_ncatbot_update: true
napcat:
  ws_uri: ws://localhost:16708
  ws_token: napcat_ws
  ws_listen_ip: localhost
  webui_uri: http://localhost:6099
  webui_token: (7Pyst9=}RO^^=|b
  enable_webui: true
  enable_update_check: false
  remote_mode: false
plugin:
  plugins_dir: plugins
  plugin_blacklist: []
  load_plugin: true
